-- -- require("java").setup()
-- -- jdtls = require "jdtls"
--
-- -- handlers = require("configs.handlers")
--
-- share_dir = os.getenv "HOME" .. "/.local/share"
-- project_name = vim.fn.fnamemodify(vim.fn.getcwd(), ":p:h:t")
-- workspace_dir = share_dir .. "/eclipse/" .. project_name
--
-- -- Set proper Java executable
-- -- java_cmd = "/usr/lib/jvm/java-21-openjdk-amd64/bin/java"
-- java_cmd = "/usr/lib/jvm/java-25-openjdk-amd64/bin/java"
-- -- java_cmd = "java"
--
-- mason_registry = require "mason-registry"
--
-- -- Helper to safely get Mason package install path (new API compatible)
-- local function get_path(pkg)
--   local ok, p = pcall(mason_registry.get_package, pkg)
--   if not ok or not p then
--     vim.notify("[jdtls] Mason package not found: " .. pkg, vim.log.levels.WARN)
--     return ""
--   end
--
--   -- Safely get install path (handle both old and new Mason APIs)
--   local install_path = nil
--   if type(p.get_install_path) == "function" then
--     install_path = p:get_install_path()
--   elseif type(p.path) == "string" then
--     install_path = p.path
--   end
--
--   if not install_path then
--     vim.notify("[jdtls] Could not determine install path for: " .. pkg, vim.log.levels.ERROR)
--     return ""
--   end
--
--   return install_path
-- end
--
-- -- vim.fn.glob Is needed to set paths using wildcard (*)
-- bundles = {
--   vim.fn.glob(get_path "java-debug-adapter" .. "/extension/server/com.microsoft.java.debug.plugin-*.jar"),
-- }
--
-- vim.list_extend(bundles, vim.split(vim.fn.glob(get_path "java-test" .. "/extension/server/*.jar"), "\n"))
--
-- jdtls_path = get_path "jdtls"
--
-- local util = require("lspconfig").util
--
-- local function find_java_root(fname)
--   local gradle_root = util.root_pattern "build.gradle.kts"(fname)
--   if gradle_root then
--     return gradle_root
--   end
--   local maven_root = util.root_pattern "pom.xml"(fname)
--   if maven_root then
--     return maven_root
--   end
--   return util.root_pattern ".git"(fname)
-- end
--
-- local module_root = find_java_root(vim.fn.expand "%:p") or vim.fn.getcwd()
-- local project_name = vim.fn.fnamemodify(module_root, ":p:h:t")
-- local workspace_dir = share_dir .. "/eclipse/" .. project_name
--
-- -- Define the function to start jdtls
-- local function start_jdtls()
--   config = {
--     cmd = {
--       java_cmd,
--       "-Declipse.application=org.eclipse.jdt.ls.core.id1",
--       "-Dosgi.bundles.defaultStartLevel=4",
--       "-Declipse.product=org.eclipse.jdt.ls.core.product",
--       "-Dlog.protocol=true",
--       "-Dlog.level=ALL",
--       "-Xms512m",
--       "-Xmx2048m",
--       "--add-modules=ALL-SYSTEM",
--       "--add-opens",
--       "java.base/java.util=ALL-UNNAMED",
--       "--add-opens",
--       "java.base/java.lang=ALL-UNNAMED",
--       "-jar",
--       vim.fn.glob(jdtls_path .. "/plugins/org.eclipse.equinox.launcher_*.jar"),
--       "-configuration",
--       jdtls_path .. "/config_linux",
--       "-data",
--       workspace_dir,
--     },
--     flags = {
--       debounce_text_changes = 150,
--       allow_incremental_sync = true,
--     },
--
--     on_init = function(client)
--       if client.config.settings then
--         client.notify("workspace/didChangeConfiguration", { settings = client.config.settings })
--       end
--     end,
--
--     init_options = {
--       bundles = bundles,
--     },
--
--     capabilities = handlers.capabilities,
--
--     on_attach = function(client, bufnr)
--       handlers.on_attach(client, bufnr)
--       if client.name == "jdtls" then
--         jdtls = require "jdtls"
--         jdtls.setup_dap { hotcodereplace = "auto" }
--         jdtls.setup.add_commands()
--         require("jdtls.dap").setup_dap_main_class_configs {}
--       end
--     end,
--
--     settings = {
--       java = {
--         signatureHelp = { enabled = true },
--         saveActions = { organizeImports = false },
--         completion = {
--           maxResults = 20,
--           favoriteStaticMembers = {
--             "org.hamcrest.MatcherAssert.assertThat",
--             "org.hamcrest.Matchers.*",
--             "org.hamcrest.CoreMatchers.*",
--             "org.junit.jupiter.api.Assertions.*",
--             "java.util.Objects.requireNonNull",
--             "java.util.Objects.requireNonNullElse",
--             "org.mockito.Mockito.*",
--           },
--         },
--         sources = {
--           organizeImports = {
--             starThreshold = 9999,
--             staticStarThreshold = 9999,
--           },
--         },
--         codeGeneration = {
--           toString = {
--             template = "${object.className}{${member.name()}=${member.value}, ${otherMembers}}",
--           },
--         },
--       },
--     },
--   }
--
--   jdtls.start_or_attach(config)
-- end
--
-- -- Auto-attach jdtls when opening Java files
-- vim.api.nvim_create_autocmd("FileType", {
--   pattern = "java",
--   callback = function()
--     print "[jdtls] Autocmd triggered"
--     vim.keymap.set("n", "<Leader>q", function()
--       vim.diagnostic.setloclist()
--     end, { noremap = true, silent = true, buffer = true })
--     vim.cmd "set filetype=java"
--     start_jdtls()
--   end,
-- })
